#!/usr/bin/env bash
set -e

soft=""
force=""

while getopts ':sf' op; do
    case $op in
        s) soft="-s";;
        f) force="-f";;
        *) exit 256;;
    esac
done

shift $((OPTIND -1))

[ -f "$1" ] || exit 1

if [[ $# == 1 ]]; then
    ln $soft $force "$(readlink -f "$1")" "$HOME/.local/bin"
else
    ln $soft $force "$(readlink -f "$1")" "$HOME/.local/bin/$2"
fi

exit 0
