#!/usr/bin/env bash

# save newline separated string into an array
website=( "$(buku -p -f 5 | column -ts$'\t' | sort -rnk1 | fzf --multi)" )

# open each website
for i in "${website[@]}"; do
    index="$(echo "$i" | awk '{print $1}')"
    buku -p "$index"
    buku -o "$index"
done

