#!/usr/bin/env bash
# fzfmenu - fzf as dmenu replacement
set -evx

c=100   # 默认列
l=12    # 默认行
i=$(xrandr | grep "[0-9]\*" | cut -dx -f1 | tr -d ' ')
i=$((i/5))

while getopts :c:l:m opt
do
    case "$opt" in
        c) c="$OPTARG";;
        l) l=$(( OPTARG + 2 ));;
        m) multi="--multi" ;;
        *) echo "Unknow options:: $opt";;
    esac
done
shift $(( OPTIND - 1 ))


input=$(mktemp -u --suffix .fzfmenu.input)
output=$(mktemp -u --suffix .fzfmenu.output)
mkfifo $input
mkfifo $output
chmod 600 $input $output

# it's better to use st here (starts a lot faster than pretty much everything else)
st -c fzfmenu -n fzfmenu -g "${c}x${l}+${i}+0000" -i -e sh -c "cat $input | \
    /usr/bin/fzf $multi --bind "ctrl-c:print-query" --reverse --info=inline | \
    tee $output" & disown

# handle ctrl+c outside child terminal window
trap "kill $! 2>/dev/null; rm -f $input $output" EXIT

cat > $input
cat $output
