#!/usr/bin/env sh

# Description: Navigate to directory using fasd
#
# Requires: fasd
#
# Shell: POSIX compliant
# Author: Marty Buchaus

if which fasd >/dev/null 2>&1; then
    printf "jump to: "
    read -r dir
    odir="$(fasd -d "$dir")"
    printf "%s" "0$odir" > "$NNN_PIPE"
else
    printf "fasd missing"
    read -r _
fi
