#!/usr/bin/env bash
set -e
tag=
content=
days=0

while getopts ":d:" op; do
    case $op in
        d) days="$OPTARG";;
        *) echo "wrong option!"
           exit 1
           ;;
   esac
   shift $((OPTIND - 1))
done

if [ $# -eq 0 ]; then
    if which fortune >/dev/null 2>&1; then
        printf "%s\n📜[1m-----------------[0m\n" "$(fortune)"
    fi
    if [ $days -eq 0 ]; then
        stup show --at today -c "plan" | sed '1d'
    elif [ $days -gt 0 ]; then
        from=$(date --date="$days days ago" +%F)
        stup log -c "plan" --from $from --to today
    else
        echo "days needed to be a non-negative interger"
        exit 2
    fi
    exit 0
elif [ $# -eq 1 ]; then
    tag="📋"
    content="$1"
else
    case $1 in
        p|plan|励志|计划|决心) tag="⛽️";;
        c|code|编程|语言) tag="🪡";;
        t|tool|工具) tag="🔩";;
        r|research|研究) tag="🧭";;
        i|idea|设想) tag="💡";;
        w|write|写作) tag="🧱";;
        n|note|备忘|笔记) tag="📍";;
        *) cat <<-EOF
				Category:
				(p)lan|励志|计划|决心
				(c)ode|编程|语言
				(t)ool|工具
				(r)esearch|研究
				(i)dea|想法
				(w)rite|写作
				(n)ote|备忘|笔记
			EOF
            return 0
        ;;
    esac
    shift 1
    content="$* [$(date +'%F %T')]"
fi

stup add today --category "plan" --note "$tag $content"

exit 0

