#!/bin/sh
# Source: https://github.com/LukeSmithxyz/st/blob/master/st-urlhandler
#
urlregex="(((http|https)://|www\\.)[^\s]*[:]?[a-zA-Z0-9./~@&%?$#=_-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

# First remove linebreaks and mutt sidebars:
urls="$(sed 's/.*│//g' | tr -d '\n' |
	grep -aEo "$urlregex" | # grep only urls as defined above.
	uniq | # Ignore neighboring duplicates.
	sed 's/^www./http:\/\/www\./g')"

[ -z "$urls" ] && exit

chosen="$(echo "$urls" | dmenu -i -p 'Follow which url?' -l 10)"

setsid linkhandler "$chosen" >/dev/null 2>&1 &
