#!/usr/bin/env bash

tfile=$(mktemp --suffix '.csv')
trap 'rm $tfile' 1 15
#wtitle="NVIM-R DataFrame Priview: $1"
#xsv table -c 30 -o "$tfile" "$1" 
cp "$1" "$tfile"
nvim -c ":set nowrap number relativenumber ft=csv" "$tfile"


